#define kOPAREN                          1
#define kCPAREN                          2
#define kNEWLINE                         3
#define kOK                              4
#define kCOMMENT_START                   5
#define kCOMMENT_END                     6
#define kCOMMENT_LINE                    7
#define kDOT                             8
#define kHEX_NUMBER                      9
#define kOCT_NUMBER                     10
#define kINT_NUMBER                     11
#define kTRUE                           12
#define kFALSE                          13
#define kCHAR_NEWLINE                   14
#define kCHAR_SPACE                     15
#define kCHAR_TAB                       16
#define kCHAR                           17
#define kSTRING                         18
#define kQUOTE                          19
#define kID                             23
